server:
  port: 8082
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.18.129:9092,192.168.18.130:9092,192.168.18.131:9092
      retries: 0
      batch-size: 4096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0
      buffer-memory: 40960
      client-id: aaa

    consumer:
      bootstrap-servers: 192.168.18.129:9092,192.168.18.130:9092,192.168.18.131:9092
      group-id: myGroup
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer